# swaybar config

bar {
	position top
	id 12759
	status_command ~/.config/sway/statusbar.sh
	colors {
		background #292522
		statusline #ECE1D7
		separator  #403A36
		focused_workspace   #292522 #867462 #ECE1D7
		active_workspace    #292522 #403A36 #C1A78E
		inactive_workspace  #292522 #403A36 #C1A78E
		urgent_workspace    #292522 #D47766 #ECE1D7
		binding_mode        #292522 #EBC06D #292522
	}
	font JetBrains Mono 12
}
