#Bashtop Melange theme
#by julbey

# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#292522"

# Main text color
theme[main_fg]="#ece1d7"

# Title color for boxes
theme[title]="#ece1d7"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#c1a78e"

# Background color of selected item in processes box
theme[selected_bg]="#403a36"

# Foreground color of selected item in processes box
theme[selected_fg]="#ece1d7"

# Color of inactive/disabled text
theme[inactive_fg]="#34302c"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#c1a78e"

# Cpu box outline color
theme[cpu_box]="#867462"

# Memory/disks box outline color
theme[mem_box]="#867462"

# Net up/down box outline color
theme[net_box]="#867462"

# Processes box outline color
theme[proc_box]="#867462"

# Box divider line and small boxes line color
theme[div_line]="#50"

# Temperature graph colors
theme[temp_start]="#85B695"
theme[temp_mid]="#ebc06d"
theme[temp_end]="#d47766"

# CPU graph colors
theme[cpu_start]="#85b695"
theme[cpu_mid]="#ebc06d"
theme[cpu_end]="#d47766"

# Mem/Disk free meter
theme[free_start]="#253333"
theme[free_mid]="#7b9695"
theme[free_end]="#89b3b6"

# Mem/Disk cached meter
theme[cached_start]="#CF9BC2"
theme[cached_mid]="#B380B0"
theme[cached_end]="#422741"

# Mem/Disk available meter
theme[available_start]="#ebc06d"
theme[available_mid]="#85b695"
theme[available_end]="#85b695"

# Mem/Disk used meter
theme[used_start]="#85b695"
theme[used_mid]="#ebc06d"
theme[used_end]="#d47766"

# Download graph colors
theme[download_start]="#273142"
theme[download_mid]="#7f91b2"
theme[download_end]="#a3a9ce"

# Upload graph colors
theme[upload_start]="#422741"
theme[upload_mid]="#b380b0"
theme[upload_end]="#cf9bc2"
