timeout = 1000
max = 100
bar_color = C1A78E
background_color = 00000000
border_color = ECE1D7
border_size = 4
anchor = bottom center
# 20% of eDP-1 height (1800px / scale 1.3 = ~1385 logical px -> ~277)
margin = 0 0 277 0
